#!/bin/bash

############################
# DDEV Commands Collection #
############################

## https://github.com/jackd248/ddev-commands-collection
## v<version/>
## dcc-autogenerated

#
# Overwrite the given config to your own needs and use a keyword to prevent this file from updates
#
composerPathApp="./app"
composerPathDeployment="."
defaultSyncSystem="stage"