#!/bin/bash

############################
# DDEV Commands Collection #
############################

## https://github.com/jackd248/ddev-commands-collection
## v<version/>
## dcc-autogenerated

black="\e[0;90m" # console commands, additional info
red="\e[0;91m" # error, attention
green="\e[0;92m" # success
yellow="\e[0;93m" # warning, documentation, faq
blue="\e[0;94m" # info
magenta="\e[0;95m" # interaction
cyan="\e[0;96m" # general
gray="\e[0;97m"
bold="\e[1m"
dim="\e[2m"
underline="\e[4m"
blink="\e[5m"
reset="\e[0m"