#!/bin/bash

############################
# DDEV Commands Collection #
############################

## https://github.com/jackd248/ddev-commands-collection
## v<version/>
## dcc-autogenerated

#
# Overwrite the given config to your own needs and use a keyword to prevent this file from updates
#
composerPathApp="/var/www/html/htdocs/typo3"
composerPathDeployment="/var/www/html/htdocs"
defaultSyncSystem="stage"
defaultSyncFileEnding="yaml"
dockerArtifactory="docker-os.artifactory.xima-services.de"
dockerImageDir="deployment"
dockerImageName=""