#!/bin/bash

############################
# DDEV Commands Collection #
############################

## https://github.com/jackd248/ddev-commands-collection
## v<version/>
## dcc-autogenerated

#
# Overwrite the given config to your own needs
#
# default
composerPathApp="/var/www/html/htdocs/typo3"
composerPathDeployment="/var/www/html/htdocs"
logPathApp="/var/www/html/htdocs/typo3/var/log/"
# sync
defaultSyncSystem="stage"
defaultSyncFileEnding="yaml"
# docker:deployment:update
dockerArtifactory="docker-os.artifactory.xima-services.de"
dockerImageDir="deployment"
dockerImageName=""