#!/bin/bash

############################
# DDEV Commands Collection #
############################

## https://github.com/jackd248/ddev-commands-collection
## v<version/>
## dcc-autogenerated
## <keep/>

#
# Overwrite the given config to your own needs
#
# default
composerPathApp="/var/www/html/app"
composerPathDeployment="/var/www/html"
# sync
defaultSyncSystem="@project.master"
# docker:deployment:update
dockerArtifactory="docker-os.artifactory.xima-services.de"
dockerImageDir="deployment"
dockerImageName=""
# copy-files
copyFilesPaths=(
  #"some/folder1/*|some/other/folder2/"
)
